### ISSUE TITLE
Plusieurs streamer pour un bot 

### ISSUE THREAD

**Issue by Azurz** [Manerr/LiveStatus#1]
Bonjour,
Je voulais savoir si il et possible de mettre plusieurs streamer sur le même bot ?
Merci 

Hello,
I wanted to know if it is possible to put several streamers on the same bot?
Thanks

**Comment by AntoninHuaut** [comment]
Hello,
Yes it's possible to have several streamers at the same time
In the config.ts file, the value associated to discord.discords is an array, you just have to clone the object and modify it

**Comment by Azurz** [comment]
A agree thank you
